language: cpp
compiler: g++

branches:
  only:
   - common

before_install:
- sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
- sudo apt-get update -qq

install:
- sudo apt-get install -qq g++-5
- export CC="g++-5"

before_script:
  - cd JVM

script:
  - make


